apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort
